### ISSUE TITLE
docs: update metrics documentation

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ignite-metrics#29]
The work tracking doc should exist in notion, but policy, standards, and processes should all be defined in the GitHub repo. 

Metrics documentation requirements make me think that the majority of docs existing in GitHub is the right decision:
- The public can access them easily
- The Public/devs can post questions/updates directed at documentation easily and publicly
- The public can be informed of updates and track update history easily
- Current and future devs can find this information and update it easily while not violating the above three items.

## Tasks

- create docs in ipfs-shipyard/ignite-metrics
   - [ ] privacy policy based on https://github.com/ipfs/ipfs-companion/blob/main/PRIVACY-POLICY.md
   - [ ] Breakdown of metrics collection intentions (opt-out and what that entails)
      - [ ] This is what the user will see
      - [ ] This is what will be collected
      - [ ] This is what won't be collected
   - [ ] basic dev consumption docs on how to use for react/non-react packages (README)
   - [ ] Link to above docs in README.md
- create single notion page under our team notion page - https://pl-strflt.notion.site/Telemetry-b005d4f217f44db3986902c67d922cf4
   - [ ] Link to all metrics items (past, present, future)
   - [ ] Link to above pages in ignite-metrics (will probably be in PR)
   - [ ] Specify team methodology and ethics for metrics collection and tools/UI used for doing so
      - [ ] specify process to follow for updating metrics.
   - [ ] Update Notion doc to address comments from Steve

**Comment by SgtPooki** [comment]
Note that I indicated in https://github.com/ipfs/ipfs-gui/issues/125#issuecomment-1370156098 that I would be specifying in the README of ignite-metrics (this repo) that I would cover 

-  This is what the user will see
-  This is what will be collected
-  This is what won't be collected

 
 but those items will be in each repo's `./docs/telemetry/CollectedData.md` documentation as specified in the `./docs/telemetry/CollectionPolicy` being added in https://github.com/ipfs-shipyard/ignite-metrics/pull/35
